<?php
/**
 * Created by PhpStorm.
 * User: fendykwan
 * Date: 10/2/17
 * Time: 11:07 AM
 */

defined('BASEPATH') OR exit('No direct script access allowed');

class Data_user extends MY_Model
{
    var $table = 'master_user';
    var $column_order = array(null,'alamat_ip','nama'); //set column field database for datatable orderable
    var $column_search = array('alamat_ip','nama'); //set column field database for datatable searchable
    var $order = array('id_user'); // default order

    public function get_datatables()
    {
        $this->_get_datatables_query();
        if($_POST['length'] != -1)
            $this->db->limit($_POST['length'], $_POST['start']);
        $this->db->where('soft_delete','0');
        $query = $this->db->get();

        return $query->result();
    }

    public function getID($ip){
        $this->db->select('id_user');
        $this->db->from($this->table);
        $this->db->where('alamat_ip',$ip);
        $this->db->where('soft_delete','0');
        $query = $this->db->get();

        if($query->num_rows() > 0)
            return $query->rows();
    }

    public function getNama($id){
        $this->db->select('nama');
        $this->db->from($this->table);
        $this->db->where('id_user',$id);
        $this->db->where('soft_delete','0');
        $query = $this->db->get();

        if($query->num_rows() > 0)
            return $query->row();
    }

    public function getUser(){
        $this->db->from($this->table);
        $this->db->where('soft_delete','0');
        $this->db->order_by('nama','ASC');
        $query = $this->db->get();

        if($query->num_rows() > 0)
            return $query->result();
    }

    public function cekIP($ip)
    {
        return parent::cekIP($ip); // TODO: Change the autogenerated stub
    }
}